Repository GSG-CF05/FoodApp-team5, pull requests merged in 2022-02, with the labels that each got.

#2 Done from add files structure relate#1
  Account/account.css
  Account/account.html
  Community/community.css
  Community/community.html
  Recipe Detail/recipe.css
  Recipe Detail/recipe.html
  index.html
  media/Page 1/p1-Rectangle 13@2x.png
  media/Page 1/p1-apple.png
  media/Page 1/p1-facebook.png
  media/Page 1/p1-google.png
  media/Page 2/p2-Asavatar.jpg
  media/Page 2/p2-Avatar (1).jpg
  media/Page 2/p2-Avatar (1).png
  media/Page 2/p2-Avatar (2).png
  media/Page 2/p2-Avatar@2x.png
  media/Page 2/p2-Card Image (1).png
  media/Page 2/p2-Card Image.jpg
  media/Page 2/p2-Card Image.png
  media/Page 2/p2-Frame 201 (1).jpg
  media/Page 2/p2-Frame 201.jpg
  media/Page 2/p2-Rectangle 13.png
  media/Page 2/p2-aAvatar.jpg
  media/Page 3/p3-Avatar.png
  media/Page 3/p3-Image.jpg
  media/Page 4/p4-Avatar.jpg
  media/Page 4/p4-Image (1).jpg
  media/Page 4/p4-Image (2).jpg
  media/Page 4/p4-Image (3).jpg
  media/Page 4/p4-Rectangle 13.jpg
  style.css
Labels: approve

#20 Upload readme file relate #19
  README.md
Labels: approved

#12 upload media query relate #11
  Account/account.css
  Account/account.html
Labels: awaiting-review

#10 Done From Recipe Detail Page relate#6
  Recipe Detail/recipe.css
  Recipe Detail/recipe.html
  Recipe-Detail/recipe.css
  Recipe-Detail/recipe.html
Labels: approve
